apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spire.server.name }}-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  bootstrap.key: {{ .Values.spire.certs.bootstrap.key | b64enc }}
