
apiVersion: batch/v1
kind: Job
metadata:
  name: gm-bootstrap-config
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # "helm.sh/hook": post-install
    # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: gm-bootstrap-config
    spec:
      restartPolicy: "Never"
      # We need a SA with read access to the `Endpoints` resource
      serviceAccountName: {{ .Values.waiter.service_account.name }}
      initContainers:
        - name: ensure-control-api
          image: {{ .Values.waiter.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: control-api
      containers:
        - image: {{ tpl .Values.bootstrap.image . }}
          name: gm-bootstrap-config
          imagePullPolicy: IfNotPresent
          command: ["/tmp/bootstrap/gm-bootstrap.sh"]
          env:
          - name: GREYMATTER_API_HOST
            value: control-api:5555
          - name: GREYMATTER_API_SSL
            value: {{ .Values.bootstrap.secret.enabled | quote }}
          - name: GREYMATTER_API_INSECURE
            value: {{ .Values.bootstrap.secret.insecure | quote }}
          - name: GREYMATTER_API_SSLCERT
            value: {{ .Values.bootstrap.secret.mount_point}}/server.crt
          - name: GREYMATTER_API_SSLKEY
            value: {{ .Values.bootstrap.secret.mount_point}}/server.key
          volumeMounts:
            - name: service-certs
              mountPath: {{ .Values.bootstrap.secret.mount_point }}
          {{- range $name, $service := .Values.services }}
          {{- if $service.controlEnabled }}
            - name: service-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/services/{{$service.serviceName}}
            - name: edge-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/edge/{{$service.serviceName}}
          {{- end }}
          {{- end }}
            - name: special-config-volume
              mountPath: /etc/config/mesh/special
            - name: bootstrap-script-volume
              mountPath: /tmp/bootstrap
      volumes:
        - name: service-certs
          secret:
            secretName: {{ .Values.bootstrap.secret.secret_name }}
            defaultMode: 0600
        {{- range $name, $service := .Values.services }}
        {{- if $service.controlEnabled }}
        - name: service-config-volume-{{ $service.serviceName }}
          configMap:
            name: service-{{ $service.serviceName }}-mesh-config
        - name: edge-config-volume-{{ $service.serviceName }}
          configMap:
            name: edge-{{ $service.serviceName }}-mesh-config
        {{- end }}
        {{- end }}
        - name: bootstrap-script-volume
          configMap:
            name: bootstrap-script
            defaultMode: 0777
        - name: special-config-volume
          configMap:
            name: special-mesh-config
      imagePullSecrets:
        - name: docker.secret