# These are the expected environment variables
#
# The Nexus information is so that the build can push the packaged charts to the Decipher Helm repo
# NEXUS_URL
# NEXUS_PASSWORD
# NEXUS_USER
#
version: 2

jobs:
  prepare-k3d:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install kubernetes
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            kubectl version --client
      - run:
          name: Set up K3d
          command: |
            wget -q -O - https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash
            make k3d
            echo "time to export tooooooo"
            export KUBECONFIG="$(k3d get-kubeconfig --name='greymatter')"
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.production.deciphernow.com/repository/helm-staging/" >> $BASH_ENV
      # - run:
      #     name: Run helm 
      #     command: |
      #       docker run --entrypoint "/usr/local/bin/helm" --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD kubectl
      - run:
          name: Run kc get nodes
          command: |
            kubectl cluster-info
            kubectl get nodes
  build-staging:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.production.deciphernow.com/repository/helm-staging/" >> $BASH_ENV
      - run:
          name: Package and Publish Catalog
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/catalog
      - run:
          name: Package and Publish Control
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/gm-data
      - run:
          name: Package and Publish GM Control API
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control-api
      - run:
          name: Package and Publish Dashboard
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/dashboard
      - run:
          name: Package and Publish JWT
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/jwt
      - run:
          name: Package and Publish JWT Gov
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/jwt-gov
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish SLO
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/slo
      - run:
          name: Package and Publish Spire Server
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/server
      - run:
          name: Package and Publish Spire Agent
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/agent
  package-and-publish-greymatter-staging:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.production.deciphernow.com/repository/helm-staging/" >> $BASH_ENV
      - run:
          name: Change Grey Matter (fabric, sense, data, spire) Requirements from local to helm-staging
          command: |
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/fabric/Chart.yaml
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/sense/Chart.yaml
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/data/Chart.yaml
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/spire/Chart.yaml
      - run:
          name: Print directory listing
          command: |
            ls -al $(pwd)
      - run:
          name: Package and Publish Fabric
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric
      - run:
          name: Package and Publish Sense
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish Spire
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire
  package-and-publish-core-hosted:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.production.deciphernow.com/repository/helm-hosted/" >> $BASH_ENV
      - run:
          name: Package and Publish Catalog
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/catalog
      - run:
          name: Package and Publish Control
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/data
      - run:
          name: Package and Publish GM Control API
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control-api
      - run:
          name: Package and Publish Dashboard
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/dashboard
      - run:
          name: Package and Publish JWT
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/jwt
      - run:
          name: Package and Publish JWT Gov
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/jwt-gov
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish SLO
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/slo
      - run:
          name: Package and Publish Spire Server
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/server
      - run:
          name: Package and Publish Spire Agent
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/agent
  package-and-publish-greymatter-hosted:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.production.deciphernow.com/repository/helm-hosted/" >> $BASH_ENV
      - run:
          name: Change Grey Matter (fabric, sense, data, spire) Requirements from local to helm-hosted
          command: |
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/fabric/Chart.yaml
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/sense/Chart.yaml
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/data/Chart.yaml
            sed -e "s|file:.*|$NEXUS_URL|" $(pwd)/spire/Chart.yaml
      - run:
          name: Package and Publish Fabric
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric
      - run:
          name: Package and Publish Sense
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish Spire
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire
workflows:
  version: 2
  build-and-publish:
    jobs:
      - prepare-k3d
      - build-staging:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /release-.*/
      - package-and-publish-greymatter-staging:
          requires:
            - build-staging
      - package-and-publish-core-hosted:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /release-2.2/
              only: /release-.*/
      - package-and-publish-greymatter-hosted:
          requires:
            - package-and-publish-core-hosted
