---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker0-sidecar
  namespace: observables
data:
  config.yaml: |-
    node:
      id: "default"
      cluster: "kafka-broker0"
      locality:
        zone: zone-default-zone
        region: default-region
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 9092
          filter_chains:
          - filters:
            - name: envoy.filters.network.kafka_broker
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.kafka_broker.v2alpha1.KafkaBroker
                stat_prefix: broker0
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: ingress_tcp
                cluster: broker0
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
            tls_context:
              common_tls_context:
                tls_certificate_sds_secret_configs:
                  - name: "spiffe://quickstart.greymatter.io/kafka-broker0"
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384
                combined_validation_context:
                  default_validation_context:
                    match_subject_alt_names:
                      exact: "spiffe://quickstart.greymatter.io/fibonacci"
                  validation_context_sds_secret_config:
                    name: "spiffe://quickstart.greymatter.io"
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
      clusters:
        - name: broker0
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: broker0
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: kafka-observables-0.kafka-observables-headless.observables.svc.cluster.local
                        port_value: 9092
        - name: xds_cluster
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: xds_cluster
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: control.default.svc.cluster.local
                        port_value: 50000
        - name: spire_agent
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: spire_agent
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      pipe:
                        path: /run/spire/socket/agent.sock
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001