
name: proxy

imagePullSecrets:
  - name: docker.secret

sidecar:
  version: 1.4.0
  image: 'docker-dev.production.deciphernow.com/deciphernow/gm-proxy:{{ $.Values.sidecar.version }}'
  port: 10808
  metrics_port: 8081
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    proxy_dynamic:
      type: 'value'
      value: 'true'
    xds_cluster:
      type: 'value'
      value: '{{ .Values.name }}'
    xds_host:
      type: 'value'
      value: 'control.greymatter3.svc.cluster.local'
    xds_port:
      type: 'value'
      value: '50000'
    spire_path:
      type: 'value'
      value: '/run/spire/socket/agent.sock'
