{{- if .Values.global.waiter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.waiter.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}