---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-sidecar-0
  namespace: observables
data:
  config.yaml: |-
    node:
      id: "default"
      cluster: "kafka-broker-0"
      locality:
        zone: zone-default-zone
        region: default-region
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 19092
          filter_chains:
            transport_socket:
              name: tls
              typed_config:
                "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
                common_tls_context:
                  tls_certificate_sds_secret_configs:
                    - name: "spiffe://quickstart.greymatter.io/kafka-broker-0"
                      sds_config:
                        api_config_source:
                          api_type: GRPC
                          grpc_services:
                            envoy_grpc:
                              cluster_name: spire_agent
                  tls_params:
                    ecdh_curves:
                      - X25519:P-256:P-521:P-384
                  combined_validation_context:
                    default_validation_context:
                      match_subject_alt_names:
                        - exact: "spiffe://quickstart.greymatter.io/fibonacci"
                        - exact: "spiffe://quickstart.greymatter.io/kafka-broker-1"
                        - exact: "spiffe://quickstart.greymatter.io/kafka-broker-2"
                    validation_context_sds_secret_config:
                      name: "spiffe://quickstart.greymatter.io"
                      sds_config:
                        api_config_source:
                          api_type: GRPC
                          grpc_services:
                            envoy_grpc:
                              cluster_name: spire_agent
            filters:
            - name: envoy.filters.network.kafka_broker
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.kafka_broker.v2alpha1.KafkaBroker
                stat_prefix: my_broker
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: my_broker_ingress_tcp
                cluster: my-broker
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
        - address:
            socket_address:
              address: 127.0.0.1
              port_value: 19192
          filter_chains:
          - filters:
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: broker1
                cluster: broker1
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
        - address:
            socket_address:
              address: 127.0.0.1
              port_value: 19292
          filter_chains:
          - filters:
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: broker2
                cluster: broker2
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
      clusters:
        - name: my-broker
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: my-broker
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: localhost
                        port_value: 9092
        - name: broker1
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: broker1
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: kafka-broker-1.observables.svc.cluster.local
                        port_value: 19192
          transport_socket:
            name: tls
            typed_config:
              "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                  - name: "spiffe://quickstart.greymatter.io/kafka-broker-0"
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384
                combined_validation_context:
                  default_validation_context:
                    match_subject_alt_names:
                      exact: "spiffe://quickstart.greymatter.io/kafka-broker-1"
                  validation_context_sds_secret_config:
                    name: "spiffe://quickstart.greymatter.io"
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
        - name: broker2
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: broker2
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: kafka-broker-2.observables.svc.cluster.local
                        port_value: 19292
          transport_socket:
            name: tls
            typed_config:
              "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                  - name: "spiffe://quickstart.greymatter.io/kafka-broker-0"
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
                tls_params:
                  ecdh_curves:
                    - X25519:P-256:P-521:P-384
                combined_validation_context:
                  default_validation_context:
                    match_subject_alt_names:
                      exact: "spiffe://quickstart.greymatter.io/kafka-broker-2"
                  validation_context_sds_secret_config:
                    name: "spiffe://quickstart.greymatter.io"
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: spire_agent
        - name: xds_cluster
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: xds_cluster
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: control.default.svc.cluster.local
                        port_value: 50000
        - name: spire_agent
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: spire_agent
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      pipe:
                        path: /run/spire/socket/agent.sock
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001