---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fibonacci-sidecar
  namespace: default
data:
  config.yaml: |-
    node:
      id: "default"
      cluster: "fibonacci"
      locality:
        zone: zone-default-zone
        region: default-region
    dynamic_resources:
      ads_config:
        api_type: GRPC
        grpc_services:
          envoy_grpc:
            cluster_name: xds_cluster
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 127.0.0.1
              port_value: 19092
          filter_chains:
          - filters:
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: broker0-proxy_tcp
                cluster: broker0-proxy
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
        - address:
            socket_address:
              address: 127.0.0.1
              port_value: 19192
          filter_chains:
          - filters:
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: broker1-proxy_tcp
                cluster: broker1-proxy
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
        - address:
            socket_address:
              address: 127.0.0.1
              port_value: 19292
          filter_chains:
          - filters:
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
                stat_prefix: broker2-proxy_tcp
                cluster: broker2-proxy
                access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                    path: "/dev/stdout"
      clusters:
        - name: broker0-proxy
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: broker0-proxy
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: kafka-broker-0.observables.svc.cluster.local
                        port_value: 19092
        - name: broker1-proxy
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: broker1-proxy
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: kafka-broker-1.observables.svc.cluster.local
                        port_value: 19192
        - name: broker2-proxy
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: broker2-proxy
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: kafka-broker-2.observables.svc.cluster.local
                        port_value: 19292
        - name: xds_cluster
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: xds_cluster
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: control.default.svc.cluster.local
                        port_value: 50000
        - name: spire_agent
          connect_timeout: 0.25s
          http2_protocol_options: {}
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: spire_agent
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      pipe:
                        path: /run/spire/socket/agent.sock
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001